/**
 * @packageDocumentation
 * @module api.functional.api.bids.my
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IBidResponse } from "../../../../../modules/bids/dto";

/**
 * Get all my bids
 *
 * Returns all bids placed by the authenticated user across all auctions.
 *
 * @tag bids
 * @security bearer
 * @returns List of user bids
 *
 * @controller BidsController.getMyBids
 * @path GET /api/bids/my
 * @accessor api.functional.api.bids.my.getMyBids
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMyBids(
  connection: IConnection,
): Promise<getMyBids.Output> {
  return true === connection.simulate
    ? getMyBids.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getMyBids.METADATA,
        template: getMyBids.METADATA.path,
        path: getMyBids.path(),
      });
}
export namespace getMyBids {
  export type Output = Primitive<Array<IBidResponse>>;

  export const METADATA = {
    method: "GET",
    path: "/api/bids/my",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/bids/my";
  export const random = (): Resolved<Primitive<Array<IBidResponse>>> =>
    typia.random<Primitive<Array<IBidResponse>>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
