/**
 * @packageDocumentation
 * @module api.functional.api.audit.summary
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  AuditSummaryQueryDto,
  AuditSummaryResponseDto,
} from "../../../../../modules/audit/dto";

/**
 * @controller AuditController.getSummary
 * @path GET /api/audit/summary
 * @accessor api.functional.api.audit.summary.getSummary
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getSummary(
  connection: IConnection,
  query: getSummary.Query,
): Promise<getSummary.Output> {
  return true === connection.simulate
    ? getSummary.simulate(connection, query)
    : PlainFetcher.fetch(connection, {
        ...getSummary.METADATA,
        template: getSummary.METADATA.path,
        path: getSummary.path(query),
      });
}
export namespace getSummary {
  export type Query = Resolved<AuditSummaryQueryDto>;
  export type Output = Primitive<Array<AuditSummaryResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/api/audit/summary",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/audit/summary";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<
    Primitive<Array<AuditSummaryResponseDto>>
  > => typia.random<Primitive<Array<AuditSummaryResponseDto>>>();
  export const simulate = (connection: IConnection, query: Query): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(query),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(query));
    return random();
  };
}
