/**
 * @packageDocumentation
 * @module api.functional.api.auctions.my_bids
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IUserBidResponse } from "@/modules/bids";
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

/**
 * Get my bids
 *
 * Returns all bids placed by the authenticated user in this auction.
 *
 * @param id Auction ID
 * @tag auctions
 * @security bearer
 * @returns List of user bids
 *
 * @controller AuctionsController.getMyBids
 * @path GET /api/auctions/:id/my-bids
 * @accessor api.functional.api.auctions.my_bids.getMyBids
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMyBids(
  connection: IConnection,
  id: string,
): Promise<getMyBids.Output> {
  return true === connection.simulate
    ? getMyBids.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...getMyBids.METADATA,
        template: getMyBids.METADATA.path,
        path: getMyBids.path(id),
      });
}
export namespace getMyBids {
  export type Output = Primitive<Array<IUserBidResponse>>;

  export const METADATA = {
    method: "GET",
    path: "/api/auctions/:id/my-bids",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/api/auctions/${encodeURIComponent(id?.toString() ?? "null")}/my-bids`;
  export const random = (): Resolved<Primitive<Array<IUserBidResponse>>> =>
    typia.random<Primitive<Array<IUserBidResponse>>>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random();
  };
}
