/**
 * @packageDocumentation
 * @module api.functional.api.bids
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as my from "./my/index";
