/**
 * @packageDocumentation
 * @module api.functional.api.auctions.leaderboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ILeaderboardEntry } from "../../../../../modules/auctions/dto";

/**
 * Get auction leaderboard
 *
 * Returns the current ranking of all active bids, sorted by amount descending.
 *
 * @param id Auction ID
 * @tag auctions
 * @returns Leaderboard entries
 *
 * @controller AuctionsController.getLeaderboard
 * @path GET /api/auctions/:id/leaderboard
 * @accessor api.functional.api.auctions.leaderboard.getLeaderboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLeaderboard(
  connection: IConnection,
  id: string,
): Promise<getLeaderboard.Output> {
  return true === connection.simulate
    ? getLeaderboard.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...getLeaderboard.METADATA,
        template: getLeaderboard.METADATA.path,
        path: getLeaderboard.path(id),
      });
}
export namespace getLeaderboard {
  export type Output = Primitive<Array<ILeaderboardEntry>>;

  export const METADATA = {
    method: "GET",
    path: "/api/auctions/:id/leaderboard",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/api/auctions/${encodeURIComponent(id?.toString() ?? "null")}/leaderboard`;
  export const random = (): Resolved<Primitive<Array<ILeaderboardEntry>>> =>
    typia.random<Primitive<Array<ILeaderboardEntry>>>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random();
  };
}
