/**
 * @packageDocumentation
 * @module api.functional.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IBalance, IBalanceResponse } from "../../../modules/users/dto";

export * as balance from "./balance/index";
export * as language from "./language/index";

/**
 * Deposit funds
 *
 * Adds the specified amount to the user's available balance.
 *
 * @param body Deposit amount
 * @tag users
 * @security bearer
 * @returns Updated balance
 *
 * @controller UsersController.deposit
 * @path POST /users/deposit
 * @accessor api.functional.users.deposit
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deposit(
  connection: IConnection,
  body: deposit.Body,
): Promise<deposit.Output> {
  return true === connection.simulate
    ? deposit.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...deposit.METADATA,
          template: deposit.METADATA.path,
          path: deposit.path(),
        },
        body,
      );
}
export namespace deposit {
  export type Body = Primitive<IBalance>;
  export type Output = Primitive<IBalanceResponse>;

  export const METADATA = {
    method: "POST",
    path: "/users/deposit",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/users/deposit";
  export const random = (): Resolved<Primitive<IBalanceResponse>> =>
    typia.random<Primitive<IBalanceResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}

/**
 * Withdraw funds
 *
 * Removes the specified amount from the user's available balance.
 *
 * @param body Withdrawal amount
 * @tag users
 * @security bearer
 * @returns Updated balance
 *
 * @controller UsersController.withdraw
 * @path POST /users/withdraw
 * @accessor api.functional.users.withdraw
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function withdraw(
  connection: IConnection,
  body: withdraw.Body,
): Promise<withdraw.Output> {
  return true === connection.simulate
    ? withdraw.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...withdraw.METADATA,
          template: withdraw.METADATA.path,
          path: withdraw.path(),
        },
        body,
      );
}
export namespace withdraw {
  export type Body = Primitive<IBalance>;
  export type Output = Primitive<IBalanceResponse>;

  export const METADATA = {
    method: "POST",
    path: "/users/withdraw",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/users/withdraw";
  export const random = (): Resolved<Primitive<IBalanceResponse>> =>
    typia.random<Primitive<IBalanceResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
