/**
 * @packageDocumentation
 * @module api.functional.api.audit.logs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  AuditLogListResponseDto,
  AuditLogQueryDto,
} from "../../../../../modules/audit/dto";

/**
 * @controller AuditController.getLogs
 * @path GET /api/audit/logs
 * @accessor api.functional.api.audit.logs.getLogs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLogs(
  connection: IConnection,
  query: getLogs.Query,
): Promise<getLogs.Output> {
  return true === connection.simulate
    ? getLogs.simulate(connection, query)
    : PlainFetcher.fetch(connection, {
        ...getLogs.METADATA,
        template: getLogs.METADATA.path,
        path: getLogs.path(query),
      });
}
export namespace getLogs {
  export type Query = Resolved<AuditLogQueryDto>;
  export type Output = Primitive<AuditLogListResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/api/audit/logs",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/audit/logs";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Primitive<AuditLogListResponseDto>> =>
    typia.random<Primitive<AuditLogListResponseDto>>();
  export const simulate = (connection: IConnection, query: Query): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(query),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(query));
    return random();
  };
}
