/**
 * @packageDocumentation
 * @module api.functional.auctions.bid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  IPlaceBid,
  IPlaceBidResponse,
} from "../../../../modules/auctions/dto";

/**
 * Place or increase bid
 *
 * Places a new bid or increases an existing bid on an active auction.
 *
 * **Rules:**
 * - Minimum bid amount must be met
 * - If you have an existing bid, the new amount must be greater than your current bid by at least the minimum increment
 * - Only the difference between your current and new bid is deducted from your balance
 * - Bids within the anti-sniping window extend the round
 *
 * @param id Auction ID
 * @param body Bid amount
 * @tag auctions
 * @security bearer
 * @returns Placed bid and updated auction
 *
 * @controller AuctionsController.placeBid
 * @path POST /auctions/:id/bid
 * @accessor api.functional.auctions.bid.placeBid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function placeBid(
  connection: IConnection,
  id: string,
  body: placeBid.Body,
): Promise<placeBid.Output> {
  return true === connection.simulate
    ? placeBid.simulate(connection, id, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...placeBid.METADATA,
          template: placeBid.METADATA.path,
          path: placeBid.path(id),
        },
        body,
      );
}
export namespace placeBid {
  export type Body = Primitive<IPlaceBid>;
  export type Output = Primitive<IPlaceBidResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auctions/:id/bid",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/auctions/${encodeURIComponent(id?.toString() ?? "null")}/bid`;
  export const random = (): Resolved<Primitive<IPlaceBidResponse>> =>
    typia.random<Primitive<IPlaceBidResponse>>();
  export const simulate = (
    connection: IConnection,
    id: string,
    body: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    assert.body(() => typia.assert(body));
    return random();
  };
}
