/**
 * @packageDocumentation
 * @module api.functional.api.audit.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { AuditLogResponseDto } from "../../../../../modules/audit/dto";

/**
 * @controller AuditController.getUserLogs
 * @path GET /api/audit/user/:userId
 * @accessor api.functional.api.audit.user.getUserLogs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserLogs(
  connection: IConnection,
  userId: string,
  limit?: number,
  skip?: number,
): Promise<getUserLogs.Output> {
  return true === connection.simulate
    ? getUserLogs.simulate(connection, userId, limit, skip)
    : PlainFetcher.fetch(connection, {
        ...getUserLogs.METADATA,
        template: getUserLogs.METADATA.path,
        path: getUserLogs.path(userId, limit, skip),
      });
}
export namespace getUserLogs {
  export type Output = Primitive<Array<AuditLogResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/api/audit/user/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (userId: string, limit?: number, skip?: number) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      limit: limit,
      skip: skip,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/api/audit/user/${encodeURIComponent(userId?.toString() ?? "null")}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Primitive<Array<AuditLogResponseDto>>> =>
    typia.random<Primitive<Array<AuditLogResponseDto>>>();
  export const simulate = (
    connection: IConnection,
    userId: string,
    limit?: number,
    skip?: number,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(userId, limit, skip),
      contentType: "application/json",
    });
    assert.param("userId")(() => typia.assert(userId));
    assert.query(() => typia.assert(limit));
    assert.query(() => typia.assert(skip));
    return random();
  };
}
