/**
 * @packageDocumentation
 * @module api.functional.api.auth.telegram.widget
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  ILoginResponse,
  ITelegramWidgetAuth,
} from "../../../../../../modules/auth/dto";

/**
 * Login via Telegram Login Widget
 *
 * Authenticates a user using data from Telegram Login Widget.
 * Creates a new user if not exists.
 *
 * @param body Telegram widget auth data
 * @tag auth
 * @returns Login response with user data and access token
 *
 * @controller AuthController.loginWithTelegramWidget
 * @path POST /api/auth/telegram/widget
 * @accessor api.functional.api.auth.telegram.widget.loginWithTelegramWidget
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function loginWithTelegramWidget(
  connection: IConnection,
  body: loginWithTelegramWidget.Body,
): Promise<loginWithTelegramWidget.Output> {
  return true === connection.simulate
    ? loginWithTelegramWidget.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...loginWithTelegramWidget.METADATA,
          template: loginWithTelegramWidget.METADATA.path,
          path: loginWithTelegramWidget.path(),
        },
        body,
      );
}
export namespace loginWithTelegramWidget {
  export type Body = Primitive<ITelegramWidgetAuth>;
  export type Output = Primitive<ILoginResponse>;

  export const METADATA = {
    method: "POST",
    path: "/api/auth/telegram/widget",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/auth/telegram/widget";
  export const random = (): Resolved<Primitive<ILoginResponse>> =>
    typia.random<Primitive<ILoginResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
