/**
 * @packageDocumentation
 * @module api.functional.users.balance
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IBalanceResponse } from "../../../../modules/users/dto";

/**
 * Get user balance
 *
 * Returns the current available and frozen balance for the authenticated user.
 *
 * @tag users
 * @security bearer
 * @returns User balance information
 *
 * @controller UsersController.getBalance
 * @path GET /users/balance
 * @accessor api.functional.users.balance.getBalance
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getBalance(
  connection: IConnection,
): Promise<getBalance.Output> {
  return true === connection.simulate
    ? getBalance.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getBalance.METADATA,
        template: getBalance.METADATA.path,
        path: getBalance.path(),
      });
}
export namespace getBalance {
  export type Output = Primitive<IBalanceResponse>;

  export const METADATA = {
    method: "GET",
    path: "/users/balance",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/users/balance";
  export const random = (): Resolved<Primitive<IBalanceResponse>> =>
    typia.random<Primitive<IBalanceResponse>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
