/**
 * @packageDocumentation
 * @module api.functional.api.auctions.system.audit
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IAuditResponse } from "../../../../../../modules/auctions/dto";

/**
 * Financial audit
 *
 * Verifies system-wide financial integrity. Checks that frozen balances
 * match active bids and no money is lost or duplicated.
 *
 * @tag auctions
 * @returns Audit results
 *
 * @controller AuctionsController.auditFinancialIntegrity
 * @path GET /api/auctions/system/audit
 * @accessor api.functional.api.auctions.system.audit.auditFinancialIntegrity
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function auditFinancialIntegrity(
  connection: IConnection,
): Promise<auditFinancialIntegrity.Output> {
  return true === connection.simulate
    ? auditFinancialIntegrity.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...auditFinancialIntegrity.METADATA,
        template: auditFinancialIntegrity.METADATA.path,
        path: auditFinancialIntegrity.path(),
      });
}
export namespace auditFinancialIntegrity {
  export type Output = Primitive<IAuditResponse>;

  export const METADATA = {
    method: "GET",
    path: "/api/auctions/system/audit",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/api/auctions/system/audit";
  export const random = (): Resolved<Primitive<IAuditResponse>> =>
    typia.random<Primitive<IAuditResponse>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
