/**
 * @packageDocumentation
 * @module api.functional.auctions.fast_bid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  IFastBidResponse,
  IPlaceBid,
} from "../../../../modules/auctions/dto";

/**
 * Place fast bid (high-performance Redis path)
 *
 * Places a bid using the Redis-cached fast path for maximum throughput.
 * Returns a simplified response without full auction state.
 * Falls back to standard bid if cache is not warmed.
 *
 * @param id Auction ID
 * @param body Bid amount
 * @tag auctions
 * @security bearer
 * @returns Fast bid result with rank
 *
 * @controller AuctionsController.placeFastBid
 * @path POST /auctions/:id/fast-bid
 * @accessor api.functional.auctions.fast_bid.placeFastBid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function placeFastBid(
  connection: IConnection,
  id: string,
  body: placeFastBid.Body,
): Promise<placeFastBid.Output> {
  return true === connection.simulate
    ? placeFastBid.simulate(connection, id, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...placeFastBid.METADATA,
          template: placeFastBid.METADATA.path,
          path: placeFastBid.path(id),
        },
        body,
      );
}
export namespace placeFastBid {
  export type Body = Primitive<IPlaceBid>;
  export type Output = Primitive<IFastBidResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auctions/:id/fast-bid",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/auctions/${encodeURIComponent(id?.toString() ?? "null")}/fast-bid`;
  export const random = (): Resolved<Primitive<IFastBidResponse>> =>
    typia.random<Primitive<IFastBidResponse>>();
  export const simulate = (
    connection: IConnection,
    id: string,
    body: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    assert.body(() => typia.assert(body));
    return random();
  };
}
