/**
 * @packageDocumentation
 * @module api.functional.auctions.leaderboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ILeaderboardQuery } from "../../../../modules/auctions/auctions.controller";
import type { ILeaderboardResponse } from "../../../../modules/auctions/dto";

/**
 * Get auction leaderboard
 *
 * Returns the current ranking of active bids in current round and past winners.
 *
 * @param id Auction ID
 * @param query Pagination parameters
 * @tag auctions
 * @returns Leaderboard with pagination and past winners
 *
 * @controller AuctionsController.getLeaderboard
 * @path GET /auctions/:id/leaderboard
 * @accessor api.functional.auctions.leaderboard.getLeaderboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLeaderboard(
  connection: IConnection,
  id: string,
  query: getLeaderboard.Query,
): Promise<getLeaderboard.Output> {
  return true === connection.simulate
    ? getLeaderboard.simulate(connection, id, query)
    : PlainFetcher.fetch(connection, {
        ...getLeaderboard.METADATA,
        template: getLeaderboard.METADATA.path,
        path: getLeaderboard.path(id, query),
      });
}
export namespace getLeaderboard {
  export type Query = Resolved<ILeaderboardQuery>;
  export type Output = Primitive<ILeaderboardResponse>;

  export const METADATA = {
    method: "GET",
    path: "/auctions/:id/leaderboard",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string, query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/auctions/${encodeURIComponent(id?.toString() ?? "null")}/leaderboard`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Primitive<ILeaderboardResponse>> =>
    typia.random<Primitive<ILeaderboardResponse>>();
  export const simulate = (
    connection: IConnection,
    id: string,
    query: Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id, query),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    assert.query(() => typia.assert(query));
    return random();
  };
}
