/**
 * @packageDocumentation
 * @module api.functional.api.auth.telegram.webapp
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  ILoginResponse,
  ITelegramWebAppAuth,
} from "../../../../../../modules/auth/dto";

/**
 * Login via Telegram Mini App
 *
 * Authenticates a user using initData from Telegram Mini App (TWA).
 * Creates a new user if not exists.
 *
 * @param body Telegram Mini App auth data
 * @tag auth
 * @returns Login response with user data and access token
 *
 * @controller AuthController.loginWithTelegramMiniApp
 * @path POST /api/auth/telegram/webapp
 * @accessor api.functional.api.auth.telegram.webapp.loginWithTelegramMiniApp
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function loginWithTelegramMiniApp(
  connection: IConnection,
  body: loginWithTelegramMiniApp.Body,
): Promise<loginWithTelegramMiniApp.Output> {
  return true === connection.simulate
    ? loginWithTelegramMiniApp.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...loginWithTelegramMiniApp.METADATA,
          template: loginWithTelegramMiniApp.METADATA.path,
          path: loginWithTelegramMiniApp.path(),
        },
        body,
      );
}
export namespace loginWithTelegramMiniApp {
  export type Body = Primitive<ITelegramWebAppAuth>;
  export type Output = Primitive<ILoginResponse>;

  export const METADATA = {
    method: "POST",
    path: "/api/auth/telegram/webapp",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/auth/telegram/webapp";
  export const random = (): Resolved<Primitive<ILoginResponse>> =>
    typia.random<Primitive<ILoginResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
