/**
 * @packageDocumentation
 * @module api.functional.api.auctions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IAuctionStatusQuery } from "../../../../modules/auctions/auctions.controller";
import type {
  IAuctionResponse,
  ICreateAuction,
} from "../../../../modules/auctions/dto";

export * as system from "./system/index";
export * as bid from "./bid/index";
export * as leaderboard from "./leaderboard/index";
export * as my_bids from "./my_bids/index";
export * as min_winning_bid from "./min_winning_bid/index";

/**
 * List all auctions
 *
 * Returns a list of all auctions, optionally filtered by status.
 *
 * @param query Query parameters for filtering
 * @tag auctions
 * @returns List of auctions
 *
 * @controller AuctionsController.findAll
 * @path GET /api/auctions
 * @accessor api.functional.api.auctions.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
  query: findAll.Query,
): Promise<findAll.Output> {
  return true === connection.simulate
    ? findAll.simulate(connection, query)
    : PlainFetcher.fetch(connection, {
        ...findAll.METADATA,
        template: findAll.METADATA.path,
        path: findAll.path(query),
      });
}
export namespace findAll {
  export type Query = Resolved<IAuctionStatusQuery>;
  export type Output = Primitive<Array<IAuctionResponse>>;

  export const METADATA = {
    method: "GET",
    path: "/api/auctions",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/auctions";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Primitive<Array<IAuctionResponse>>> =>
    typia.random<Primitive<Array<IAuctionResponse>>>();
  export const simulate = (connection: IConnection, query: Query): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(query),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(query));
    return random();
  };
}

/**
 * Get auction details
 *
 * Returns detailed information about a specific auction including round states.
 *
 * @param id Auction ID
 * @tag auctions
 * @returns Auction details
 *
 * @controller AuctionsController.findOne
 * @path GET /api/auctions/:id
 * @accessor api.functional.api.auctions.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return true === connection.simulate
    ? findOne.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...findOne.METADATA,
        template: findOne.METADATA.path,
        path: findOne.path(id),
      });
}
export namespace findOne {
  export type Output = Primitive<IAuctionResponse>;

  export const METADATA = {
    method: "GET",
    path: "/api/auctions/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/api/auctions/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (): Resolved<Primitive<IAuctionResponse>> =>
    typia.random<Primitive<IAuctionResponse>>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random();
  };
}

/**
 * Create new auction
 *
 * Creates a new auction with the specified configuration.
 * The sum of items across all rounds must equal totalItems.
 *
 * @param body Auction configuration
 * @tag auctions
 * @security bearer
 * @returns Created auction
 *
 * @controller AuctionsController.create
 * @path POST /api/auctions
 * @accessor api.functional.api.auctions.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        body,
      );
}
export namespace create {
  export type Body = Primitive<ICreateAuction>;
  export type Output = Primitive<IAuctionResponse>;

  export const METADATA = {
    method: "POST",
    path: "/api/auctions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/api/auctions";
  export const random = (): Resolved<Primitive<IAuctionResponse>> =>
    typia.random<Primitive<IAuctionResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}

/**
 * Start auction
 *
 * Starts a pending auction. The first round begins immediately.
 *
 * @param id Auction ID
 * @tag auctions
 * @security bearer
 * @returns Started auction
 *
 * @controller AuctionsController.start
 * @path POST /api/auctions/:id/start
 * @accessor api.functional.api.auctions.start
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function start(
  connection: IConnection,
  id: string,
): Promise<start.Output> {
  return true === connection.simulate
    ? start.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...start.METADATA,
        template: start.METADATA.path,
        path: start.path(id),
      });
}
export namespace start {
  export type Output = Primitive<IAuctionResponse>;

  export const METADATA = {
    method: "POST",
    path: "/api/auctions/:id/start",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/api/auctions/${encodeURIComponent(id?.toString() ?? "null")}/start`;
  export const random = (): Resolved<Primitive<IAuctionResponse>> =>
    typia.random<Primitive<IAuctionResponse>>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random();
  };
}
