/**
 * Stub classes for nestjs-asyncapi decorators.
 * Actual schemas are generated by typia and injected at runtime.
 */

// Client → Server
export class AuthPayload {}
export class PlaceBidPayload {}
export class AuctionIdPayload {}

// Server → Client
export class AuthResponse {}
export class BidResponse {}
export class AuctionRoomResponse {}
export class NewBidEvent {}
export class AuctionUpdateEvent {}
export class CountdownEvent {}
export class AntiSnipingEvent {}
export class RoundStartEvent {}
export class RoundCompleteEvent {}
export class AuctionCompleteEvent {}
