/**
 * @packageDocumentation
 * @module api.functional.users.language
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  ILanguageResponse,
  ILanguageUpdate,
} from "../../../../modules/users/dto";

/**
 * Update user language preference
 *
 * Sets the user's preferred language for the app and notifications.
 *
 * @param body Language code
 * @tag users
 * @security bearer
 * @returns Updated language code
 *
 * @controller UsersController.updateLanguage
 * @path PUT /users/language
 * @accessor api.functional.users.language.updateLanguage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateLanguage(
  connection: IConnection,
  body: updateLanguage.Body,
): Promise<updateLanguage.Output> {
  return true === connection.simulate
    ? updateLanguage.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...updateLanguage.METADATA,
          template: updateLanguage.METADATA.path,
          path: updateLanguage.path(),
        },
        body,
      );
}
export namespace updateLanguage {
  export type Body = Primitive<ILanguageUpdate>;
  export type Output = Primitive<ILanguageResponse>;

  export const METADATA = {
    method: "PUT",
    path: "/users/language",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/users/language";
  export const random = (): Resolved<Primitive<ILanguageResponse>> =>
    typia.random<Primitive<ILanguageResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
