/**
 * @packageDocumentation
 * @module api.functional.auth.telegram
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as widget from "./widget/index";
export * as webapp from "./webapp/index";
