/**
 * @packageDocumentation
 * @module api.functional.auctions.min_winning_bid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IMinWinningBidResponse } from "../../../../modules/auctions/dto";

/**
 * Get minimum winning bid
 *
 * Returns the minimum bid amount needed to be in a winning position for the current round.
 *
 * @param id Auction ID
 * @tag auctions
 * @returns Minimum winning bid amount
 *
 * @controller AuctionsController.getMinWinningBid
 * @path GET /auctions/:id/min-winning-bid
 * @accessor api.functional.auctions.min_winning_bid.getMinWinningBid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMinWinningBid(
  connection: IConnection,
  id: string,
): Promise<getMinWinningBid.Output> {
  return true === connection.simulate
    ? getMinWinningBid.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...getMinWinningBid.METADATA,
        template: getMinWinningBid.METADATA.path,
        path: getMinWinningBid.path(id),
      });
}
export namespace getMinWinningBid {
  export type Output = Primitive<IMinWinningBidResponse>;

  export const METADATA = {
    method: "GET",
    path: "/auctions/:id/min-winning-bid",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/auctions/${encodeURIComponent(id?.toString() ?? "null")}/min-winning-bid`;
  export const random = (): Resolved<Primitive<IMinWinningBidResponse>> =>
    typia.random<Primitive<IMinWinningBidResponse>>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random();
  };
}
