/**
 * @packageDocumentation
 * @module api.functional.api.transactions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  ITransactionQuery,
  ITransactionResponse,
} from "../../../../modules/transactions/dto";

/**
 * Get transaction history
 *
 * Returns a paginated list of transactions for the authenticated user,
 * ordered by most recent first.
 *
 * @param query Pagination parameters
 * @tag transactions
 * @security bearer
 * @returns List of transactions
 *
 * @controller TransactionsController.getTransactions
 * @path GET /api/transactions
 * @accessor api.functional.api.transactions.getTransactions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getTransactions(
  connection: IConnection,
  query: getTransactions.Query,
): Promise<getTransactions.Output> {
  return true === connection.simulate
    ? getTransactions.simulate(connection, query)
    : PlainFetcher.fetch(connection, {
        ...getTransactions.METADATA,
        template: getTransactions.METADATA.path,
        path: getTransactions.path(query),
      });
}
export namespace getTransactions {
  export type Query = Resolved<ITransactionQuery>;
  export type Output = Primitive<Array<ITransactionResponse>>;

  export const METADATA = {
    method: "GET",
    path: "/api/transactions",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/api/transactions";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Primitive<Array<ITransactionResponse>>> =>
    typia.random<Primitive<Array<ITransactionResponse>>>();
  export const simulate = (connection: IConnection, query: Query): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(query),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(query));
    return random();
  };
}
