/**
 * @packageDocumentation
 * @module api.functional.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IHealthResponse } from "../../../modules/health/health.controller";

/**
 * @controller HealthController.check
 * @path GET /health
 * @accessor api.functional.health.check
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function check(connection: IConnection): Promise<check.Output> {
  return true === connection.simulate
    ? check.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...check.METADATA,
        template: check.METADATA.path,
        path: check.path(),
      });
}
export namespace check {
  export type Output = Primitive<IHealthResponse>;

  export const METADATA = {
    method: "GET",
    path: "/health",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/health";
  export const random = (): Resolved<Primitive<IHealthResponse>> =>
    typia.random<Primitive<IHealthResponse>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
